### ISSUE TITLE
Unable to connect to EV3-G via Wired

### ISSUE THREAD

**Issue by laurensvalk** [ev3dev/lms2012-compat#35]
I have the EVB up and running. The lms2012 boots and runs fine. The demo program works. (Awesome!)

It's connected via ethernet, which correctly shows up as "wired" in the on screen WiFi settings menu. An ip adress is listed and I can ping it from my host PC.

My host PC is a Virtual Box Windows 8.1 machine. This machine can ping the EVB successfully as well (it sees the local network).

But it won't show up as a device in EV3-G.

Any suggestions to debug this?

**Comment by dlech** [comment]
hmm... it's working for me. I haven't installed the recent EV3-G update yet though (1.2.2, I believe). If you have Wireshark installed, you could sniff the network traffic.

**Comment by dlech** [comment]
Also, I'm on windows 10, but I don't think that should make a difference.

How do you have the VirtualBox network connection configured? I have successfully used this in Bridge mode. If you are using NAT mode, that could be the problem.

**Comment by WasabiFan** [comment]
IDK if it matters, but I believe that Windows 8 didn't include an mDNS driver while Windows 10 does.

**Comment by dlech** [comment]
Nope, this has to do with UDP broadcast packets.

**Comment by laurensvalk** [comment]
> How do you have the VirtualBox network connection configured? I have successfully used this in Bridge mode. If you are using NAT mode, that could be the problem.

This was it. Thanks!
