### ISSUE TITLE
Strange back button behavior within Brickman

### ISSUE THREAD

**Issue by laurensvalk** [ev3dev/lms2012-compat#44]
With "ev3dev-jessie-ev3-lsm2012-2016-12-30", pressing the back button once (and briefly) always brings up the shutdown menu, from any initial menu location in Brickman, as if there was a long press.

Since the cancel is the default selection, you'd think you could close the menu with the enter button, but I need to press it twice.

I'm pretty sure this didn't happen yesterday with "snapshot-ev3dev-jessie-ev3-generic-2016-12-21.img".

@jabrena, can you confirm this? If not, I'll reflash the card to be absolutely certain it's not the physical button being stuck.

**Comment by jabrena** [comment]
HI @laurensvalk, yes one hour ago, when I was tested lms-compact, I felt it. It seems that the ev3 buttons was very sensitive. And many times appeared the modal window to shutdown.

**Comment by dlech** [comment]
This seems to be some sort of interaction between brickman (and therefore ncurses) and the new kernel. I'm not sure exactly what it could be though because buttons seem to work OK in `lms2012-compat` and with `evtest`.

**Comment by laurensvalk** [comment]
For reference, this still occurs with [this version](https://github.com/ev3dev/lms2012-compat/releases/tag/ev3dev-jessie%2F1.99.3)

**Comment by dlech** [comment]
This issue is actually not specific to lms2012-compat, but it seems to be more noticeable with the lms2012 kernel.

Fix has been released in `ev3devkit_0.4.3`.
