### ISSUE TITLE
Unable to download programs after changing brick name from EV3-G

### ISSUE THREAD

**Issue by laurensvalk** [ev3dev/lms2012-compat#46]
After changing the EV3 Brick name (from 82ccf01e7aab to Marvin) from the connection menu in the lower right of the EV3 PC software, programs fail to download.

It looks like the name doesn't actually change on the EV3 brick, which may be intentional (?).

The ability to upload programs is restored after changing the name entry back to 82ccf01e7aab.

**Comment by dlech** [comment]
> It looks like the name doesn't actually change on the EV3 brick, which may be intentional (?).

See #23

**Comment by dlech** [comment]
> programs fail to download.

Is there an error message? Is the message the same as #42?

**Comment by laurensvalk** [comment]
It was error code 0 as in #42, yes, but for some reason I can't reproduce this now.

**Comment by dlech** [comment]
OK, closing as a duplicate. If you have any new info, please post on #42.
