### ISSUE TITLE
Medium Motor is auto-detected as Large Motor

### ISSUE THREAD

**Issue by laurensvalk** [ev3dev/lms2012-compat#47]
Medium Motor is auto-detected as Large Motor. 

To reproduce: connect a medium motor to any motor port, and check the lms2012 Port View app. 

(Likewise, EV3-G will show a yellow exclamation mark near the Medium Motor block, thinking that none is attached)

4.9.0-ev3dev-bpo-stretch-r2-ev3-lms2012 FW V1.99C

**Comment by dlech** [comment]
Depending on the position of the motor shaft, a medium motor could be detected as a medium motor or a large motor.

**Comment by dlech** [comment]
Fix has been released in kernel 4.9.0-ev3dev-bpo-stretch-r3-ev3-lms2012
