### ISSUE TITLE
Motor turns too fast

### ISSUE THREAD

**Issue by laurensvalk** [ev3dev/lms2012-compat#48]
With this program, the motor should run slowly at 10%, but it rotates at maximum speed. It does stop after 5 rotations. Same happens in reverse (-10%). Speed ("current power") measurement seems okay as well.

![slowmotor](https://cloud.githubusercontent.com/assets/12326241/21594224/530ada3e-d120-11e6-8bf8-588f423ee32b.png)

Observed with a clean 4.9.0-ev3dev-bpo-stretch-r2-ev3-lms2012 image,  FW V1.99C.

**Comment by dlech** [comment]
Fix has been released in kernel 4.9.0-ev3dev-bpo-stretch-r3-ev3-lms2012
