### ISSUE TITLE
How to use Bluetooth and USB on lms2012 compat?

### ISSUE THREAD

**Issue by laurensvalk** [ev3dev/lms2012-compat#55]
Can you follow the same steps as with regular ev3dev, or are different steps required?

And once it works, are USB and Bluetooth connected ev3 devices expected to show up in EV3-G as USB/BT? Or as WiFi since they are more like networked devices?

Or does it activate some other USB mode when you launch lms2012 so it acts like a normal EV3?

Right now, the usb shows up as MAC address 12:00:00:00:00:00 which doesn't match "The MAC address will always start with 12:16:53, so choose that one".

My tests so far have been done with WiFi.

Update: I am able to connect to my host using Bluetooth, ssh, launch lms2012, and then connect to EV3-G with usb after installing [this version](https://github.com/ev3dev/lms2012-compat/releases/tag/ev3dev-jessie%2F1.99.3). I am able to launch programs now.

So technically it's not an issue, but I'm still a bit confused as to what the appropriate connection methods are.

**Comment by dlech** [comment]
> Can you follow the same steps as with regular ev3dev, or are different steps required?

Different steps are required. ev3dev uses TCP/IP network connections for all types of communication (USB/Bluetooth/Wi-Fi), whereas lms2012 only uses it for Wi-Fi.

> And once it works, are USB and Bluetooth connected ev3 devices expected to show up in EV3-G as USB/BT?

Yes.

> Or as WiFi since they are more like networked devices?

I suppose we could make it work like that, but currently it is not possible. Well, it might be possible with Bluetooth.

> Or does it activate some other USB mode when you launch lms2012 so it acts like a normal EV3?

lms2012-comapt takes over the USB port and should act like a "normal" EV3.

> So technically it's not an issue, but I'm still a bit confused as to what the appropriate connection methods are.

The connection methods should be the same as a "normal" EV3, so if you want a remote terminal and use lms2012-comapt, you will need to use Wi-Fi like a "normal" EV3. (And I suppose Bluetooth can be used for multiple things simultaneously, so you might get away with having a network connection using Bluetooth and using it in lms2012-comat at the same time).

**Comment by laurensvalk** [comment]
Got it, thanks for clearing it up!

I currently use Bluetooth for SSH in order to start lms2012, and then USB for EV3-G.
