### ISSUE TITLE
Unable to start lms2012 with latest stretch image

### ISSUE THREAD

**Issue by laurensvalk** [ev3dev/lms2012-compat#58]
I seem to be unable start lms2012 compat with the [latest stretch image](https://oss.jfrog.org/list/oss-snapshot-local/org/ev3dev/brickstrap/2017-06-27/snapshot-ev3dev-stretch-ev3-generic-2017-06-27.img.xz).

Following the steps in the readme, I get this mismatch:

```
robot@ev3dev:~$ uname -a
Linux ev3dev 4.9.34-ev3dev-1.2.0-ev3 #1 PREEMPT Mon Jun 26 20:45:12 CDT 2017 armv5tejl GNU/Linux
robot@ev3dev:~$ sudo FK_MACHINE="LEGO MINDSTORMS EV3 + lms2012-compat" flash-kernel
[sudo] password for robot: 
Using DTB: da850-lego-ev3-lms2012.dtb
Installing /usr/lib/linux-image-4.9.34-ev3dev-1.2.0-ev3/da850-lego-ev3-lms2012.dtb into /boot/dtbs/4.9.34-ev3dev-1.2.0-ev3/da850-lego-ev3-lms2012.dtb
Installing new da850-lego-ev3-lms2012.dtb.
Kernel /boot/vmlinuz-4.9.34-ev3dev-1.2.0-ev3 does not match any of the expected flavors (ev3-lms2012), therefore not writing it to flash.
```

If I try to start lms2012 after reboot, the command is not found.

**Comment by dlech** [comment]
Problem 1: Kernel /boot/vmlinuz-4.9.34-ev3dev-1.2.0-ev3 does not match any of the expected flavors (ev3-lms2012), therefore not writing it to flash.

This is a bug in `flash-kernel`. https://github.com/ev3dev/flash-kernel/blob/9dd7f4e192905a1620bece96a694682d6dd6819d/db/all.db#L735 should be:

    Kernel-Flavors: ev3

So, to fix temporarily, 

    sudo vi /usr/share/flash-kernel/db/all.db

and edit line 735

---

Problem 2: no `lms2012` command.

I guess it is not installed by default (yet).

    sudo apt update
    sudo apt install lms2012-compat

**Comment by laurensvalk** [comment]
Thanks, this solves the problem!

I'm afraid l'll have to open a separate issue for the fact that lms2012 doesn't get past the starting screen, though :wink:

**Comment by dlech** [comment]
updated flash-kernel package has been released and snapshots starting today should have lms2012-comapt installed by default on EV3.
