### ISSUE TITLE
Cannot flash to drive

### ISSUE THREAD

**Issue by pipothy** [ev3dev/lms2012-compat#62]
Hi. Just attempted to flash the napshot-ev3dev-stretch-ev3-generic-2017-07-26.img.xz file to my SD card and got a humongous error. I deleted everything off the card previously. Any idea why I might have got this error? Sorry, I'm not the most tech savvy person!
![flasherror](https://user-images.githubusercontent.com/6817670/28720781-16ed1868-73a6-11e7-8255-fb745917839c.png)

**Comment by dlech** [comment]
I would suggest reporting this error to Etcher at <https://github.com/resin-io/etcher/issues>.

In the mean time, you could try using this program instead: https://sourceforge.net/projects/win32diskimager/

**Comment by WasabiFan** [comment]
@dlech will Win32 Disk Imager work given that we don't ship `.zip` files anymore?

**Comment by dlech** [comment]
Good point. You might have to use 7Zip to extract the image file first.

**Comment by pipothy** [comment]
Hi,

Used 7Zip to extract the image file... no avail, same error.

**Comment by dlech** [comment]
The Win32DiskImager program gave the same error as the Etcher program?

**Comment by pipothy** [comment]
Win32DiskImager worked. Bizarre.

**Comment by dlech** [comment]
The guys working on Etcher are really great, so I hope you will still report this error to them even though you got your image flashed.

**Comment by pipothy** [comment]
Of course! Happy to help them :)

**Comment by pipothy** [comment]
Just had a look and it seems I was accidentally in some beta distribution from ages back. That could be it. I'll try it later and see if it works. If not, I'll post it to etcher!
