### ISSUE TITLE
Data Log file appears to be corrupt on Import

### ISSUE THREAD

**Issue by edleft** [ev3dev/lms2012-compat#68]
Running BBB+FatCat EVB Cape, macOS Education Edition EV3-G

Program:
- Data logger block with Lego Temp Sensor, 1 sample/sec
- Loop for some # samples, then end
- Explicit Data Log Off block after the Loop

--
Jenko

Attached:
1. .rdf files
2. error dialog on Data Log Import (Experiment)

[TempData.zip](https://github.com/ev3dev/lms2012-compat/files/1238727/TempData.zip)

![datalogger_error](https://user-images.githubusercontent.com/16468305/29518577-c8868628-862e-11e7-8c53-c2566ef88ba9.png)

**Comment by dlech** [comment]
Fix released in ev3dev-stretch/1.99.6
