### ISSUE TITLE
lms2012 startup fails with: could not load memory driver (post-Aug 26 builds)

### ISSUE THREAD

**Issue by edleft** [ev3dev/lms2012-compat#70]
Running stretch build on BBB with FatCat Cape (uEnv.txt set to cape=evb-lms2012): 
1. Aug 26 image works (lms2012 starts up)
2. Sept 1 and later images fail with this:
``
root@ev3dev:~/bin# lms2012
Could not open '/sys/devices/platform/evb-battery/power_supply/evb-battery/current_now': No such file or directory
** (process:946): WARNING **: Could not start graphics: No supported video driver plugins found
** (process:946): WARNING **: Falling back to memory driver
** (process:946): ERROR **: Could not load memory driver
Trace/breakpoint trap
root@ev3dev:~/bin#
``
3. Same error upon upgrading with apt-get from Aug 26 build. Also reproduced on BBB+Quest Cape (uEnv.xt: cape=quest-lms2012).

**Comment by dlech** [comment]
fix released in v1.99.7
