### ISSUE TITLE
lms2012 startup looking for connman service

### ISSUE THREAD

**Issue by edleft** [ev3dev/lms2012-compat#71]
For tracking purposes.
- Running Aug 26 stretch build (due to issue #70) on BBB + FatCat Cape
- Using Ethernet on BBB
- lms2012 starts up fine if connman running but if using networking service (connman disabled), get the following on startup:
``
oot@ev3dev:~# lms2012
Failed to find system power supply
Error getting technologies: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name net.connman was not provided by any .service files
(process:767): GLib-GIO-CRITICAL **: g_dbus_proxy_call_sync_internal: assertion 'error == NULL || *error == NULL' failed
[Invalid UTF-8] Error getting technologies: $\x88\xad\xb6$\x88\xad\xb6roxy_call_sync_internal: assertion 'error == NULL || *error == NULL' faiX
*** Error in `lms2012': double free or corruption (!prev): 0x01ee0b88 ***
Aborted
root@ev3dev:~#
``
- Workaround is to use connman for all IP config

**Comment by dlech** [comment]
fix released in v1.99.7
