### ISSUE TITLE
Create user leds subsystem driver for platforms without hardware LEDs

### ISSUE THREAD

**Issue by dlech** [ev3dev/lms2012-compat#9]
The FatcatLab EVB does not have LEDS, but instead uses part of the display as a virtual LED.

This will be similar to the user sensor driver already in ev3dev. We should probably use a character device though instead of sysfs.

**Comment by dlech** [comment]
The configfs part is done.

**Comment by dlech** [comment]
I have started a conversation about this on the LKML: https://lkml.org/lkml/2016/7/25/505

Configfs might not be the way to go. Maybe something more like uinput where devices are created using the dev node.

**Comment by dlech** [comment]
Submitted the patch...

https://lkml.org/lkml/2016/9/5/942

**Comment by dlech** [comment]
https://lkml.org/lkml/2016/9/8/713

**Comment by dlech** [comment]
https://lkml.org/lkml/2016/9/9/588

**Comment by dlech** [comment]
<s>https://git.kernel.org/cgit/linux/kernel/git/j.anaszewski/linux-leds.git/commit/?h=for-next&id=7618b35c65a3976520cb74ad7b8d22c0b5fe3f73</s>

**Comment by WasabiFan** [comment]
Just curious: what do you do now that you've gotten the patch accepted into the mainline kernel? Apply it to the kernel source that the BBB is running yourself, or maybe rebase that commit onto it? And what do you do when you then want to merge in the real upstream commit, given that you would have directly conflicting changes?

**Comment by dlech** [comment]
It's not in mainline yet, this is the leds maintainers tree. This means that it will first (hopefully) get tested by some folks interested in LEDs. Then it should make its way into the linux-next tree that is the main testing ground for almost everything before it makes it in the mainline kernel. If all goes well, this should land in Linus' tree in the next merge window, which is coming up soon.

Once it does actually make it into the mainline kernel, I will cherry-pick the commit and apply it to all of the ev3dev kernels. Whenever we rebase on the mainline kernel that includes this patch (4.10 or higher), git will notice and drop the cherry-picked commit. For quite some time now, I have been rebasing the kernels instead of merging to keep all of the ev3dev commits on top where people can actually see them without having to search through hundreds of thousands of commits (there have literally be over 200k commits since we started ev3dev with a 3.2 kernel).

**Comment by WasabiFan** [comment]
Oh, that makes sense. Thanks for explaining! It's funny looking at some of the kernel repos because GitHub just gives up listing the contributors and instead lists it as infinity :laughing:

**Comment by dlech** [comment]
https://lkml.org/lkml/2016/9/16/620

**Comment by dlech** [comment]
https://git.kernel.org/cgit/linux/kernel/git/j.anaszewski/linux-leds.git/commit/?h=for-4.10&id=21ab38ffcc3c0a1542e4191490e831120a39cc2c

**Comment by dlech** [comment]
https://lwn.net/Articles/703785/

**Comment by dlech** [comment]
This version is slightly modified as compared to how it is described in the LWN article:

https://git.kernel.org/cgit/linux/kernel/git/j.anaszewski/linux-leds.git/commit/?h=for-next&id=c62bc3bb5507618ffb61b6e5159ee8298598ee48

**Comment by dlech** [comment]
:tada: https://github.com/torvalds/linux/commit/e381322b0190c1253d347de3f28b5c37756fb651

**Comment by rhempel** [comment]
Hey that is great news! Congratulations!
